const menu = [
  {
    id: 1,
    title: "Spaghetti Bolognese",
    category: "Main Course",
    price: 12.99,
    img: "spaghetti.jpg",
    desc: "Classic Italian pasta dish with ground beef and tomato sauce.",
  },
  {
    id: 2,
    title: "Caesar Salad",
    category: "Appetizers",
    price: 8.99,
    img: "caesar_salad.jpg",
    desc: "Fresh romaine lettuce, homemade croutons, and Parmesan cheese tossed in a tangy Caesar dressing.",
  },
  {
    id: 3,
    title: "Margherita Pizza",
    category: "Main Course",
    price: 14.99,
    img: "margherita_pizza.jpg",
    desc: "Traditional Italian pizza topped with fresh tomatoes, mozzarella cheese, and basil.",
  },
  {
    id: 4,
    title: "Chicken Alfredo",
    category: "Main Course",
    price: 15.99,
    img: "chicken_alfredo.jpg",
    desc: "Grilled chicken breast served with creamy Alfredo sauce over fettuccine pasta.",
  },
  {
    id: 5,
    title: "Garlic Bread",
    category: "Appetizers",
    price: 4.99,
    img: "garlic_bread.jpg",
    desc: "Toasted French bread topped with garlic butter and herbs.",
  },
  {
    id: 6,
    title: "Beef Burger",
    category: "Main Course",
    price: 10.99,
    img: "beef_burger.jpg",
    desc: "Juicy beef patty with lettuce, tomato, onion, and your choice of cheese.",
  },
  {
    id: 7,
    title: "Vegetable Stir-Fry",
    category: "Main Course",
    price: 11.99,
    img: "vegetable_stir_fry.jpg",
    desc: "Assorted fresh vegetables sautéed in a flavorful sauce, served with steamed rice.",
  },
  {
    id: 8,
    title: "French Onion Soup",
    category: "Appetizers",
    price: 6.99,
    img: "french_onion_soup.jpg",
    desc: "Traditional French soup made with caramelized onions, beef broth, and melted cheese on top.",
  },
  {
    id: 9,
    title: "Fish and Chips",
    category: "Main Course",
    price: 13.99,
    img: "fish_and_chips.jpg",
    desc: "Deep-fried battered fish fillets served with crispy fries and tartar sauce.",
  },
  {
    id: 10,
    title: "Chocolate Brownie",
    category: "Desserts",
    price: 7.99,
    img: "chocolate_brownie.jpg",
    desc: "Warm, fudgy chocolate brownie topped with vanilla ice cream and chocolate sauce.",
  },
];

export default menu;
